sudo: required
services:
  - docker

before_install:
  - docker build -t vladpavlovski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vladpavlovski/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-288376452317"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
